version: '3.6'
services:
  core:
    container_name: cosmos_core
    image: hsfl2/core
    logging:
      driver: "local"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - cwnetwork
    restart: unless-stopped
    volumes:
      - bin:/root/cosmos/bin
      - resources:/root/cosmos/resources

volumes:
  bin: {}
  resources: {}

networks:
  cwnetwork:
    name: cosmos_cwnetwork
    driver: bridge