version: '3.6'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmos_core
    networks:
      - cwnetwork
    restart: unless-stopped
    volumes:
      - bin:/root/cosmos/bin
      - resources:/root/cosmos/resources

volumes:
  bin: {}
  resources: {}

networks:
  cwnetwork:
    name: cosmos_cwnetwork
    driver: bridge