version: '3.6'
services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=hsfl
      - DOCKER_INFLUXDB_INIT_BUCKET=SOH_Bucket
      #- DOCKER_INFLUXDB_INIT_RETENTION=
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=INFLUXDBINITADMINTOKEN
    ports:
      - '8086:8086'
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2:/.influxdb2

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=hsfl
      - DOCKER_INFLUXDB_INIT_BUCKET=SOH_Bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=INFLUXDBINITADMINTOKEN
      - AGENT_BEACON_PORT=10095
      - AGENT_SOH_PORT=10096
      - SIMDATA_PORT=10097
    ports:
      - '10095:10095/udp'
      #- '10097:10097/udp'
    volumes:
    - ./tools/cosmos-web/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - ./tools/cosmos-web/soh_parser.star:/soh_parser.star:ro
    - ./tools/cosmos-web/beacon_parser.star:/beacon_parser.star:ro
    - ./tools/cosmos-web/simdata_parser.star:/simdata_parser.star:ro
    depends_on:
      - influxdb
    links:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DEFAULT_APP_MODE=development
    links:
      - influxdb
    ports:
      - '3000:3000'
      #- '8086:8086'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./tools/cosmos-web/grafana-plugins:/var/lib/grafana/plugins

  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmos
    restart: always
    volumes:
      - bin:/home/cosmos/bin
  
  web_backend:
    build:
      context: ./tools/cosmos-web/backend/
      dockerfile: Dockerfile
      target: base
    #platform: linux/x86_64 # tentative used for macOS M1 to compile graphana plugins
    container_name: cosmos_web_backend
    ports:
      - '10090:10090'
    volumes:
      - ./tools/cosmos-web/grafana-plugins:/grafana-plugins
      - ./tools/cosmos-web/backend/src:/home/node/app/src
      - ./tools/cosmos-web/backend/nodemon.json:/home/node/app/nodemon.json
    command: npm run dev


volumes:
  bin: {}
  grafana_data: {}
  influxdb2: {}
